### ISSUE TITLE
"Topic 'nlu_fallback' not found, is NLU backend up to date ?"

### ISSUE THREAD

**Issue by vprima** [vertigo-io/vertigo-bot-factory#25]
When I start to speak to the bot after a training, this is the stack trace I get : 

java.lang.NullPointerException: Topic 'nlu_fallback' not found, is NLU backend up to date ?
	at java.util.Objects.requireNonNull(Objects.java:347) ~[?:?]
	at io.vertigo.core.lang.Assertion.isNotNull(Assertion.java:101) ~[vertigo-core-3.0.0.jar:?]
	at io.vertigo.chatbot.engine.BotEngine.getTopicFromNlu(BotEngine.java:236) ~[classes/:?]
	at io.vertigo.chatbot.engine.BotEngine.doHandleExpected(BotEngine.java:186) ~[classes/:?]
	at io.vertigo.chatbot.engine.BotEngine.handleExpected(BotEngine.java:168) ~[classes/:?]
	at io.vertigo.chatbot.engine.BotEngine.runTick(BotEngine.java:95) ~[classes/:?]
	at io.vertigo.chatbot.executor.manager.ExecutorManager.handleUserMessage(ExecutorManager.java:133) ~[classes/:?]
	at io.vertigo.chatbot.executor.webservices.TalkWebService.talk(TalkWebService.java:46) ~[classes/:?]
	[...]

Our fallback script, once exported, is : 
begin sequence
say "Désolé, je n&#39;ai pas compris."
topic:start
end sequence

Is there an issue with this script ? If not, is there something we can do to avoid the error ?

Thank you.

**Comment by vprima** [comment]
Turns out this issue appears when you don't have enough topics to train your chatbot. I tried with 2 topics and I don't have the issue anymore.
